#!/bin/bash
set -euo pipefail
FORCE_T1="${FORCE_T1:-}"
MAKEFILE="steps/Makefile"

#csv
CSV="$HOME/patient_data.csv"
#dowloaded examination data
PARTICIPANTS="participants.tsv"
RAWDATA="rawdata"
#saving the logs
LOGDIR="$HOME/logs"
mkdir -p "$LOGDIR"
FAILCSV="$LOGDIR/pipeline_failures"

#definition of columnames
if [[ ! -f "$FAILCSV" ]]; then
  echo "TAJ,SESID,STEP,ERROR" > "$FAILCSV"
fi

#venv
PYRAD_VENV="pyrad_venv/bin/activate"
RADIOMICS_SCRIPT="run_radiomics.py"

#gender specific mask, with the 3 cm sphere
VOI_MALE="$HOME/male_liver_average_trh05_voi.nii.gz"
VOI_FEMALE="$HOME/female_liver_average_trh05_voi.nii.gz"

#params.yaml file, and define output folders and files
PARAMS_YAML="$HOME/params_adc.yaml"
RAD_OUTDIR="$HOME/out_integrated"
RAD_OUTCSV="$RAD_OUTDIR/radiomics.csv"
RAD_MASKDIR="$RAD_OUTDIR/masks"
mkdir -p "$RAD_OUTDIR"

#define makefile outputs
TOTALSEG_OUT_ROOT="output"

#first two row from .csv
#all the patients in .csv
#tail -n +2 "$CSV" | cut -d ';' -f 3 | while read -r i

sed -n '1,136p' "$CSV" | cut -d ';' -f 3 | while read -r i
#tail -n +2 "$CSV" | cut -d ';' -f 3 | head -n 2 | while read -r i
do
    [[ -z "$i" ]] && continue

    if [[ ${#i} -eq 8 ]]; then
        i="0$i"
    fi

    gender="$(grep -F "$i" "$PARTICIPANTS" | tail -n 1 | cut -f 3 || true)"
    [[ -z "$gender" ]] && gender="M"

    subjdir="$RAWDATA/sub-$i"
    [[ ! -d "$subjdir" ]] && continue

    cd "$subjdir"

    mapfile -t ADC_LIST < <(
        find . -type f -name '*.json' -exec grep -Hi 'adc' {} \; \
        | cut -d ':' -f 1 | sed 's/\.json$/.nii.gz/' | awk '!seen[$0]++' \
    )

    mapfile -t T1_LIST < <(
        grep -r --include="*.json" "ProtocolName" . \
        | grep -iE 't1' \
        | cut -d ':' -f 1 | sort -u | sed 's/\.json$/.nii.gz/'
    )

    for adc in "${ADC_LIST[@]}"
    do
        #sesid="$(echo "$adc" | sed -E 's/.*_ses-([^_]+)_.*/\1/')"
	sesid="$(printf '%s' "$adc" | sed -E 's|.*[/_](ses-[^/_]+).*|\1|')"
	if [[ "$sesid" != ses-* ]]; then
	    echo "WARN: sesid parse failed for adc=$adc -> sesid='$sesid'" >&2
	    continue
	fi
        #t1="$(printf "%s\n" "${T1_LIST[@]}" | grep -F "$sesid" || true)"
	#t1="$(printf "%s\n" "${T1_LIST[@]}" | grep -F "$sesid" | head -n 1 || true)"
	if [[ -n "$FORCE_T1" ]]; then
	    echo "FORCED T1: $FORCE_T1"
	    t1="$FORCE_T1"
	else
	    t1_candidates="$(printf "%s\n" "${T1_LIST[@]}" | grep -F "$sesid" || true)"

	    t1="$(printf "%s\n" "$t1_candidates" | grep -i 'echo-1' | head -n 1 || true)"
	    [[ -z "$t1" ]] && t1="$(printf "%s\n" "$t1_candidates" | head -n 1 || true)"
	fi

        if [[ -z "$t1" ]]; then
            echo "No T1 found for ADC=$adc (ses=$sesid), skipping"
            continue
        fi

        echo "--------------------------------------------------"
        echo "TAJ: $i"
        echo "Session: $sesid"
        echo "Gender: $gender"
        echo "ADC: $adc"
        echo "T1 : $t1"

    #The Makefile is executed using the all target. The workflow starts from the all entry point, and if any step fails, the error is written to the error log.
    if ! make -f "$MAKEFILE" all \
	Gender="$gender" \
	T1Nifti="$t1" \
	ADC="$adc" \
	TAJ="$i" \
	SESID="$sesid"
    then
	echo "FAILED: TAJ=$i SESID=$sesid -> continuing"
	echo "$i,$sesid,make_all,make_failed" >> "$FAILCSV"
    continue
    fi


#The .nii.gz files generated by the Makefile were located.
        ADC_IN_ATLAS="$TOTALSEG_OUT_ROOT/$i/adc/${i}_${sesid}_adc_in_atlas.nii.gz"
#If such a file is not available, the radiomic feature calculation is skipped.
        if [[ ! -f "$ADC_IN_ATLAS" ]]; then
            echo "Radiomics skip (nincs adc_in_atlas): $ADC_IN_ATLAS"
            continue
        fi

#The virtual environment was activated, and the previously defined script was executed with the required options and input parameters.
        source "$PYRAD_VENV"
        python "$RADIOMICS_SCRIPT" \
          --adc_in_atlas "$ADC_IN_ATLAS" \
          --taj "$i" \
          --sesid "$sesid" \
          --gender "$gender" \
          --voi_male "$VOI_MALE" \
          --voi_female "$VOI_FEMALE" \
          --params "$PARAMS_YAML" \
          --rawdata "$RAWDATA" \
          --out_csv "$RAD_OUTCSV" \
          --out_masks_dir "$RAD_MASKDIR"
    done
done

echo "Kész. Radiomics CSV: $RAD_OUTCSV"
